name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   secrets: read # This job needs to read secrets (e.g., SSH key)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Get your code from the repository

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0 # Action to set up SSH agent
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        chmod 600 ~/.ssh/known_hosts
        echo "This did something :D"