name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Get your code from the repository

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0 # Action to set up SSH agent
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        echo "This did something :D"

    - name: Deploy Config File to EC2
      run: |
        set -euxo pipefail

        # Define variables for clarity (optional, but good practice)
        LOCAL_CONFIG_PATH="config.py"
        REMOTE_DESTINATION_PATH="/home/${{ secrets.EC2_USER }}/my-config.conf"

        echo "Deploying ${LOCAL_CONFIG_PATH} to EC2..."
        scp -o StrictHostKeyChecking=no "${LOCAL_CONFIG_PATH}" "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${REMOTE_DESTINATION_PATH}"
        echo "Config file deployed successfully to ${REMOTE_DESTINATION_PATH}."